### ISSUE TITLE
bot gets stuck after the second or third ip

### ISSUE THREAD

**Issue by Mishchap** [perfilrobo/hexbot#40]
So the previous version I had was working perfectly (except with clan servers with no logs). - fixed that up sorry xD
Now it only goes to the second or third ip (while installing viruses) and it stops working. And the task manager fills up. I do have the latest version but I'm unsure why it doesn't work correctly. I tried the timer but it didn't work. 
Did I break the bot by accident or is it something else?

**Comment by Mishchap** [comment]
since nobody has replied i presume you want logs?

VK. Startup (background is ready)
protectable_element_detector.js:44 Mixed Content: The page at 'https://legacy.hackerexperience.com/internet?view=logs' was loaded over HTTPS, but requested an insecure image 'http://legacy.hackerexperience.com/img/xlogo.png.pagespeed.ic.nwil56PAQB.png'. This content should also be served over HTTPS.
protectable_element_detector.js:44 Mixed Content: The page at 'https://legacy.hackerexperience.com/internet?view=logs' was loaded over HTTPS, but requested an insecure image 'http://legacy.hackerexperience.com/img/xmenu-active.png.pagespeed.ic.OWkkrNyQCo.png'. This content should also be served over HTTPS.
protectable_element_detector.js:44 Mixed Content: The page at 'https://legacy.hackerexperience.com/internet?view=logs' was loaded over HTTPS, but requested an insecure image 'http://legacy.hackerexperience.com/images/xhe16.png.pagespeed.ic.WuUDsY20JZ.png'. This content should also be served over HTTPS.
protectable_element_detector.js:44 Mixed Content: The page at 'https://legacy.hackerexperience.com/internet?view=logs' was loaded over HTTPS, but requested an insecure image 'http://legacy.hackerexperience.com/images/xbreadcrumb.png.pagespeed.ic.IHZAMzRhXY.png'. This content should also be served over HTTPS.
4content.js:15 VK. Startup (background is ready)
Enabler.js:100  [  0.002s] [studio.sdk] 
Enabler.js:100  [  0.005s] [studio.sdk] 
content.js:15 VK. Startup (background is ready)
2Enabler.js:100  [  0.036s] [studio.sdk] Asset properties have been set by host.
2Enabler.js:100  [  0.036s] [Enabler] ad visible
jSpaghetti.min.js:1 jSpaghetti debug: Gotoif returned false (uploader:upload:@cleanMyAccessClues:3)  
jSpaghetti.min.js:1 jSpaghetti debug: Sequence is reset (adRemover:removeAds)  
VM3853:1 'webkitIDBCursor' is deprecated. Please use 'IDBCursor' instead.
jSpaghetti.min.js:1 jSpaghetti debug: Waiting for page to reload (uploader:upload:@cleanMyAccessClues:4)  
jSpaghetti.min.js:1 jSpaghetti debug: Running command "adRemover:removeAds:0:0:removeAds"
2Enabler.js:100  [  1.071s] [studio.sdk] Using default ad parameters in test environment. Simulating local events.
jSpaghetti.min.js:1 jSpaghetti debug: Sequence is terminated (adRemover:removeAds)  
content.js:37 UA. Wait for background...

this is all i can retrieve from the console, I hope this helps.

**Comment by gresendesa** [comment]
Ok. I guess the problem is here:

jSpaghetti.min.js:1 jSpaghetti debug: **Waiting for page to reload** (uploader:upload:@cleanMyAccessClues:4)

The is waiting indefinitely. I'm already anylizing this problem.

**Comment by Mishchap** [comment]
As far as I know the tab wasn't inactive, but maybe I should double check.
Thanks for looking into this, I appreciate it.

**Comment by Mishchap** [comment]
tried the new update, got this
VK. Startup (background is ready)
jSpaghetti.min.js:1 jSpaghetti debug: Waiting for page to reload (uploader:upload:@cleanMyUploadClues:5)  
jSpaghetti.min.js:1 jSpaghetti debug: Sequence is reset (adRemover:removeAds)  
VM2991:1 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
2content.js:15 VK. Startup (background is ready)
jSpaghetti.min.js:1 jSpaghetti debug: Running command "adRemover:removeAds:0:0:removeAds"
procedures.js:15 Uncaught TypeError: Cannot read property 'length' of null
jSpaghetti.min.js:1 jSpaghetti debug: Sequence is terminated (adRemover:removeAds)  
12procedures.js:15 Uncaught TypeError: Cannot read property 'length' of null
19procedures.js:15 Uncaught TypeError: Cannot read property 'length' of null

i thought it was because i had no timer, so i tried it again, and got this
http://prntscr.com/b7r2qn - thought a screenshot would be easier.

**Comment by gresendesa** [comment]
Could you send me just the ips with which you are having this crashes? gresendesa@gmail.com
Maybe I have to handle these ip's particularities.

**Comment by gresendesa** [comment]
The second problem you reported is now fixed: https://github.com/perfilrobo/hexbot/releases/tag/v0.1.15.1

**Comment by Mishchap** [comment]
still broken, ill pm you the ips im using atm
http://prntscr.com/b85izd

**Comment by Mishchap** [comment]
uhhh, its still broken xD
http://prnt.sc/b8nil9
i think it just gets hung when it joins a server

**Comment by gresendesa** [comment]
I'm going to rewrite the uploader module today. I will merge it to the webcrawler.

**Comment by Mishchap** [comment]
thanks, hopefully that will fix the issue im having.

**Comment by gresendesa** [comment]
Ok Yoda :~

**Comment by gresendesa** [comment]
@Mishchap try again, please. I've just released the latest update

**Comment by Mishchap** [comment]
oh man... it's still happening http://prntscr.com/b9bwyz
would it be because i have an ip reset qued and ready to go?

**Comment by saulens22** [comment]
It can happen when doing missions too. I think it's because game redirects you into your log/software, not into page bot expects. When task manager is empty, everything works fine.

**Comment by Mishchap** [comment]
ill see if it works without the ip reset qued, i hope that it just wasnt because of that this whole time :/
dont want to be causing problems for nothing

**Comment by Mishchap** [comment]
okay it still broke even without an ip reset qued
http://prntscr.com/b9cf4y

**Comment by gresendesa** [comment]
Hey. Help me please. I really wanna fix it.
Let's break it down. 
Does the log progress bar appear before the crash?
Well, the logs are telling me the progress bar is appearing. But the logs don't make sense to me once the bot get crashed. :(

**Comment by Mishchap** [comment]
so like, it logs into the server after showing the progress bar,  and clears the log, and it also shows the progress of it clearing. but after that it stops.

**Comment by gresendesa** [comment]
What a odd! The game site sometimes has a strange behavior.
Anyway I'm going to replace the {"wait": "_forPageToReload"} command for {"wait": _forTheSignal} command. I think it must work.

**Comment by Mishchap** [comment]
It stops after a couple of ips. Hopefully replacing the code will fix it xD

**Comment by gresendesa** [comment]
Give just 20 min

**Comment by Mishchap** [comment]
sure :p

**Comment by gresendesa** [comment]
Ok. Check it out: https://github.com/perfilrobo/hexbot/releases/tag/v0.1.16.2
Give me your feedback

**Comment by Mishchap** [comment]
giving it a whirl, ill wait 10 mins, if it doesnt work before that, ill tell you

**Comment by Mishchap** [comment]
was working okay, but it got stuck again - http://prntscr.com/b9cuf4

**Comment by gresendesa** [comment]
Hey, What if the bot never waits for log process? I can make it works under background using AJAX.

**Comment by Mishchap** [comment]
what do you mean by that? I'm only asking because I don't know much about coding.

**Comment by gresendesa** [comment]
@Mishchap It was just a thought. Hey check the latest version out. I think the problem you've been reported is permanently fixed.

**Comment by Mishchap** [comment]
when i get home ill see if it works, thanks for really trying to solve my issue!

**Comment by Mishchap** [comment]
it works! thanks for fixing it @gresendesa :)
hopefully i wont have this issue again xD

**Comment by gresendesa** [comment]
You're welcome. :)

**Comment by Mishchap** [comment]
xD hahahah
it seems to log out after 100 ips or so, or stops when there is one of those verification things
ill just keep on running it and try and see when it stops, i doubt its the bot.
it just might be the website logging me out on purpose or something like that. 
or maybe its just me, ill see if its a net issue or something else :p

**Comment by gresendesa** [comment]
@Mishchap reopen if necessary.
